#####################################################################
#  _     _ __   __  _____   ______ _____ ______         _______
#  |_____|   \_/   |_____] |_____/   |   |     \ |      |______
#  |     |    |    |       |    \_ __|__ |_____/ |_____ |______
#
#####################################################################

general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	after_sleep_cmd = loginctl dispatch dpms on
}

# Set monitor light to minimum
listener {
	timeout = 600
	on-timeout = brightnessctl -s set 10
	on-resume = brightnessctl -r
}

# Lock screen
listener {
	timeout = 1800
	on-timeout = loginctl lock-session
}

# Turn off screen
listener {
	timeout = 2100
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}

# Suspend PC -> Verify the possibility to disable it with a script when necessary... For now, it's set to 3 hours of inactivity -> I can't restart PC without reboot. Need to figure that out
#listener {
#	timeout = 10800
#	on-timeout = systemctl suspend
#}
