###################################################################
#  _     _ __   __  _____   ______        _______ __   _ ______
#  |_____|   \_/   |_____] |_____/ |      |_____| | \  | |     \
#  |     |    |    |       |    \_ |_____ |     | |  \_| |_____/
#
###################################################################

# ----------------------------
# Monitors
# ----------------------------
$monitor1 = DP-1
$monitor2 = HDMI-A-1
monitor = $monitor1, 1920x1080@144, 0x0, 1
monitor = $monitor2, 1920x1080@75, 1920x0, 1

# ----------------------------
# Programs
# ----------------------------
$terminal = foot
$browser = firefox
$discord = discord
$steam = steam
$menu = wofi --show
$cliphist = cliphist list | wofi --dmenu | cliphist decode | wl-copy
$gimp = gimp
$calc = qalculate-gtk

# ----------------------------
# Source Files
# ----------------------------
source = ~/.config/hypr/conf/colors.conf
source = ~/.config/hypr/conf/start.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/window_workspace.conf

# ----------------------------
# Environment Variables
# ----------------------------
env = xcursor_size,10
env = hyprcursor_size,10

ecosystem:no_update_news = true
