return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    opts = {
        sync_install = true,
        highlight = {
            enable = true,
        },
        indent = {
            enable = true,
        },
        additional_vim_regex_highlighting = false,
        auto_install = true,
        ensure_installed = {
            "c",
            "cpp",
            "lua",
            "vim",
            "vimdoc",
            "diff",
            "sql",
            "rust",
            "go",
            "html",
            "css",
            "scss",
            "javascript",
            "python",
            "bash",
            "zsh",
            "markdown",
            "toml",
            "csv",
            "xml",
            "yaml",
            "json",
            "comment",
            "hyprlang",
            "make",
        },
    },
}
