#####################################################
#  |      _______ __   __  _____  _     _ _______
#  |      |_____|   \_/   |     | |     |    |
#  |_____ |     |    |    |_____| |_____|    |
#
####################################################

# ----------------------------
# General
# ----------------------------
general {
    layout = dwindle
    gaps_in = 2
    gaps_out = 3
    border_size = 2
    resize_on_border = false
    allow_tearing = false

    col.active_border = rgba(1c3f7ce6) rgba(7eb1ffe6) 270deg
    col.inactive_border = rgba(0c0c0cb3)
}

# ----------------------------
# Decoration
# ----------------------------
decoration {
    rounding = 13
    active_opacity = 0.95
    inactive_opacity = 0.95
    fullscreen_opacity = 0.95
    dim_inactive = true
    dim_strength = 0.4525

    shadow {
        enabled = true
        range = 4
        render_power = 2
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 4
        passes = 1
        vibrancy = 0.1696
    }

    #screen_shader = ~/.config/hypr/scripts/screenShader.frag
}

# ----------------------------
# Input
# ----------------------------
input {
    # Keyboard behavior
    kb_layout = br
    kb_variant = abnt2
    kb_options = ctrl:nocaps, caps:none
    numlock_by_default = true

    # Mouse behavior
    follow_mouse = 2
    sensitivity = 0
}

# ----------------------------
# Animation -> default. got no time bruh
# ----------------------------
animations {
    enabled = true

    # default animations, see https://wiki.hyprland.org/configuring/animations/ for more
    bezier = mybezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, mybezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

# ----------------------------
# Dwindle configurations
# ----------------------------
dwindle {
    pseudotile = true # mainmod + p
    preserve_split = true
}

# ----------------------------
# Master configurations
# ----------------------------
master {
    mfact = 0.6
    new_status = slave
}

# ----------------------------
# Misc
# ----------------------------
misc {
    disable_hyprland_logo = true # no anime girl
    col.splash = rgba(1c3f7ce6)
    splash_font_family = FiraMonoNerdFont
    font_family = FiraMonoNerdFont
    force_default_wallpaper = 0
    focus_on_activate = false
    mouse_move_focuses_monitor = false
}


# ----------------------------
# Cursor
# ----------------------------
cursor {
    no_warps = true
}

# ----------------------------
# Ecosystem
# ----------------------------
ecosystem {
    no_update_news = true
    no_donation_nag = true
}
