######################################################################################## 
#   _______ _______ _______  ______ _______      _______  _____   _____  _______
#   |______    |    |_____| |_____/    |         |_____| |_____] |_____] |______
#   ______|    |    |     | |    \_    |         |     | |       |       ______|
#                                                                             
######################################################################################## 

# Applications
exec-once = $browser
exec-once = mako
exec-once = hyprpaper
exec-once = $terminal
exec-once = wl-paste --watch cliphist store
#exec-once = hypridle

# Scripts
exec-once = ~/.config/waybar/launch.sh
exec-once = ~/.config/hypr/scripts/hyprpaper_change.sh > ~/.cache/hyprpaper_change.log
