###########################################
#  _____ __   _  _____  _     _ _______
#    |   | \  | |_____] |     |    |   
#  __|__ |  \_| |       |_____|    |   
#                                     
###########################################
input {
    # Keyboard behavior
    kb_layout = br
    kb_variant = abnt2 
    kb_options = ctrl:nocaps, caps:none 
    numlock_by_default = true

    # Mouse behavior
    follow_mouse = 2
    sensitivity = 0
}
