#####################################################################################################
#  _ _ _ _ _  _ ___  ____ _ _ _ ____    \      _ _ _ ____ ____ _  _ ____ ___  ____ ____ ____ ____ 
#  | | | | |\ | |  \ |  | | | | [__      \     | | | |  | |__/ |_/  [__  |__] |__| |    |___ [__  
#  |_|_| | | \| |__/ |__| |_|_| ___]      \    |_|_| |__| |  \ | \_ ___] |    |  | |___ |___ ___] 
#                                                                                               
#####################################################################################################

# Window
windowrulev2 = suppressevent maximize, class:(.*) # you'll probably like this.
windowrulev2 = monitor $monitor1, workspace:1|3
windowrulev2 = monitor $monitor2, workspace:2|4|6
windowrulev2 = workspace 1, class:foot
windowrulev2 = workspace 2, class:firefox
windowrulev2 = workspace 3, fullscreen 1, class:^steam$
windowrulev2 = workspace 4, class:Google.*
windowrulev2 = workspace 5, class:Gimp
windowrulev2 = workspace 6, class:discord
windowrulev2 = opaque 1, class:firefox|discord|steam
windowrulev2 = opaque 1, fullscreen:1, class:negative:foot.*
windowrulev2 = float, class:^qalc.*

# Workspace
workspace = 1, monitor:$monitor1, persistent:true, name:Work
workspace = 2, monitor:$monitor2, persistent:true, gapsin:0, gapsout:1, rounding:false, name:Firefox
workspace = 3, monitor:$monitor1, decorate:false, name:Gaming
workspace = 4, monitor:$monitor2, decorate:false, name:DBeaver
workspace = 6, monitor:$monitor2, gapsin:0, gapsout:1, rounding:false, name:Discord
